"""Modify Database base structure

Revision ID: c01f623ef8fb
Revises: e4334735b802
Create Date: 2025-01-23 18:47:50.828689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01f623ef8fb'
down_revision = 'e4334735b802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chatbot_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('is_handled_by_bot', sa.Boolean(), nullable=True),
    sa.Column('transferred_to_agent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('direction', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sent_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('message_status_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('message_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ticket', ['ticket_id'], ['id'])
        batch_op.create_foreign_key(None, 'contact', ['contact_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['sent_by'], ['id'])
        batch_op.drop_column('status_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_constraint('queue_message_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('queue_agent_id_fkey', type_='foreignkey')
        batch_op.drop_column('message_id')
        batch_op.drop_column('agent_id')
        batch_op.drop_column('priority')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('queue_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ticket_status_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('priority_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('ticket_status_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('ticket_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ticket_status', ['ticket_status_id'], ['id'])
        batch_op.create_foreign_key(None, 'priority', ['priority_id'], ['id'])
        batch_op.create_foreign_key(None, 'contact', ['contact_id'], ['id'])
        batch_op.create_foreign_key(None, 'queue', ['queue_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['assigned_to'], ['id'])
        batch_op.drop_column('status_id')
        batch_op.drop_column('contact')
        batch_op.drop_column('title')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ticket_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('ticket_status_name_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    with op.batch_alter_table('ticket_status', schema=None) as batch_op:
        batch_op.create_unique_constraint('ticket_status_name_key', ['name'])
        batch_op.alter_column('code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ticket_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('ticket_status_id_fkey', 'ticket_status', ['status_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('name')
        batch_op.drop_column('priority_id')
        batch_op.drop_column('ticket_status_id')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('queue_id')
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('queue_agent_id_fkey', 'user', ['agent_id'], ['id'])
        batch_op.create_foreign_key('queue_message_id_fkey', 'message', ['message_id'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('message_status_id_fkey', 'message_status', ['status_id'], ['id'])
        batch_op.drop_column('is_read')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('sent_by')
        batch_op.drop_column('direction')
        batch_op.drop_column('ticket_id')
        batch_op.drop_column('contact_id')

    op.drop_table('chatbot_control')
    op.drop_table('role')
    op.drop_table('priority')
    op.drop_table('contact')
    # ### end Alembic commands ###
